name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        echo ${{ env.GOOGLE_CLIENT_ID }}
        echo ${{ vars.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET=${{ env.GOOGLE_CLIENT_SECRET }} GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }} GOOGLE_API_KEY=${{ env.GOOGLE_API_KEY }} cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
